name: Staging CD

on:
  push:
    branches: ["staging"]
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: '3.8'
    - run: pip install django
    - shell: bash
      run: pwd 
    - run: python manage.py runserver &
        
    